export const gameSelector = (state: SessionStore) => ({
  textFieldValue: state.textFieldValue,
  setTextFieldValue: state.setTextFieldValue,
  chars: state.chars,
  setChars: state.setChars,
  gameEndTime: state.gameEndTime,
  setGameEndTime: state.setGameEndTime,
  gameStartTime: state.gameStartTime,
  setGameStartTime: state.setGameStartTime,
  charColors: state.charColors,
  setCharColors: state.setCharColors,
  nailedChars: state.nailedChars,
  setNailedChars: state.setNailedChars,
  capturedChars: state.capturedChars,
  setCapturedChars: state.setCapturedChars,
  randomIndex: state.randomIndex,
  setRandomIndex: state.setRandomIndex,
  remainingTime: state.remainingTime,
  setRemainingTime: state.setRemainingTime,
  initialTimerValue: state.initialTimerValue,
  backspaceDisabled: state.backspaceDisabled,
  setBackspaceDisabled: state.setBackspaceDisabled,
  words: state.words,
  capturedWords: state.capturedWords,
  setWords: state.setWords,
  setCapturedWords: state.setCapturedWords,
  setNailedWords: state.setNailedWords,
});